In [1]:
#imports
import geopandas as gpd
# initial position shapfile path
#fp = "/home/samin/data/shapefiles/senseflux_intersectpoint_500m_offshore.shp"
fp = "/home/samin/data/shapefiles/intersectionpoints/GLB_Bdry_buff10km__lh_shore_NOAA_70k_Intersect_snaped.shp"
# Read file using gpd.read_file
data = gpd.read_file(fp)

In [2]:
data

,FID_GLB_Bd,arcid,grid_code,from_node,to_node,FID_lh_sho,LENGTH,S_SCALE,REV_DATE,POINT_X,POINT_Y,Watershed_,geometry
0,-85,57952,1,43065,43180,1512,0.632,80000,3/91,-84.723778,45.780149,1,"MULTIPOINT (979760.289 1024028.548, 979760.289..."
1,-85,60221,1,43085,44570,1512,0.632,80000,3/91,-84.720259,45.765519,2,MULTIPOINT (979738.775 1022491.094)
2,-85,61285,1,44755,45313,1512,0.632,80000,3/91,-84.666133,45.744976,3,MULTIPOINT (983824.774 1020100.441)
3,-85,61712,1,44756,45608,1512,0.632,80000,3/91,-84.649457,45.742696,4,MULTIPOINT (985183.861 1019807.068)
4,-85,63406,1,42613,46695,1512,0.632,80000,3/91,-84.598685,45.718945,5,MULTIPOINT (989091.896 1017216.996)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,-82,148561,1,110939,112110,1736,0.466,120000,6/90,-82.442101,43.039771,230,MULTIPOINT (1164303.613 720773.327)
230,-82,148599,1,112139,110934,1736,0.466,120000,6/90,-82.441044,43.038346,231,MULTIPOINT (1164349.297 720685.368)
231,-82,149337,1,112139,112760,1736,0.466,120000,6/90,-82.436305,43.031368,232,MULTIPOINT (1164820.547 719885.588)
232,-82,149337,1,112139,112760,1742,0.052,120000,6/90,-82.431921,43.025005,233,MULTIPOINT (1165297.681 719012.773)
233,-82,149574,1,112787,112985,1742,0.052,120000,6/90,-82.422245,43.008666,234,MULTIPOINT (1166044.586 717393.459)

In [4]:
# Rename col 0 to lon and col 1 to lat
data.rename(columns={"POINT_X":"lon", "POINT_Y":"lat"}, inplace=True)

In [5]:
# Relocate the first column with 360 coordinates
#relocate the first column with 360 coordinates
data["lon"] = data["lon"] % 360

# add two new coloumns
data["depth"] = 0.0
data["group_id"] = 1
# specify the output directory to save the data
out_path = '/home/samin/data/FVCOME_OUTPUT/simulations/horon/input/converted_senseflux_intersectpoint_5km_offshore_updated.dat'
# Specify the order of columns and save them
out_col_order = ["group_id", "lon","lat", "depth"]
data.loc[:, out_col_order].to_csv(out_path, sep = ' ', index = False, header=False)